import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

interface PrototypeEntry {
  ticket: string;
  title: string;
  module: string;
  route: string;
  status: 'draft' | 'review' | 'approved';
  components: string[];
}

@Component({
  selector: 'app-prototype-gallery',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <div class="gallery">
      <div class="gallery__header">
        <h2>Prototype Gallery</h2>
        <p class="gallery__subtitle">
          All wireframes generated by the RPP Pipeline. Click to preview.
        </p>
      </div>

      <div class="gallery__empty" *ngIf="prototypes.length === 0">
        <i class="pi pi-inbox"></i>
        <h3>No prototypes yet</h3>
        <p>
          Run <code>Claude Code</code> with a Jira ticket to generate your first wireframe.
        </p>
      </div>

      <div class="gallery__grid" *ngIf="prototypes.length > 0">
        <a
          *ngFor="let proto of prototypes"
          [routerLink]="proto.route"
          class="gallery__card"
        >
          <div class="gallery__card-header">
            <span class="gallery__ticket">{{ proto.ticket }}</span>
            <span class="gallery__status" [attr.data-status]="proto.status">
              {{ proto.status }}
            </span>
          </div>
          <h3 class="gallery__card-title">{{ proto.title }}</h3>
          <div class="gallery__module">{{ proto.module }}</div>
          <div class="gallery__components">
            <span *ngFor="let comp of proto.components" class="gallery__component-tag">
              {{ comp }}
            </span>
          </div>
        </a>
      </div>
    </div>
  `,
  styleUrl: './prototype-gallery.component.scss',
})
export class PrototypeGalleryComponent {
  prototypes: PrototypeEntry[] = [];
}
